apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-deployment
  labels:
    app: availability
spec:
  replicas: 3
  selector:
    matchLabels:
      app: availability
  template:
    metadata:
      labels:
        app: availability
    spec:
      containers:
      - name: availability
        image: devmentors/pacco.services.availability
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: availability
spec:
  selector:
    app.kubernetes.io/name: availability
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376