---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-deployment
  namespace: microservices
  labels:
    app: availability
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: availability
  template:
    metadata:
      labels:
        app: availability
    spec:
      containers:
        - name: availability
          image: devmentors/pacco.services.availability
          ports:
          - containerPort: 80