---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveries-deployment
  namespace: microservices
  labels:
    app: deliveries
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: deliveries
  template:
    metadata:
      labels:
        app: deliveries
    spec:
      containers:
        - name: deliveries
          image: devmentors/pacco.services.deliveries
          ports:
          - containerPort: 80