---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveries-deployment
  namespace: microservices
  labels:
    app: deliveries
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: deliveries
  template:
    metadata:
      labels:
        app: deliveries
    spec:
      containers:
        - name: deliveries
          image: devmentors/pacco.services.deliveries
          resources:
            requests:
              cpu: "25m"
              memory: "128Mi"
            limits:
              cpu: "75m"
              memory: "256Mi"
          ports:
          - containerPort: 80
          envFrom:
          - configMapRef:
              name: deliveries-configmap
