---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  namespace: microservices
  labels:
    app: orders
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: devmentors/pacco.services.orders
          ports:
          - containerPort: 80